databases:
  - name: ai-mock-interviews-db
    databaseName: aimock
    user: aimock_user
    plan: starter

services:
  - type: web
    name: ai-mock-interviews-backend
    env: docker
    rootDir: backend
    plan: starter
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: FRONTEND_ORIGIN
        value: https://surya-ray1.github.io
      - key: APP_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: ai-mock-interviews-db
          property: connectionString
    # Dockerfile in backend/ will handle build and start
    postDeployCommand: |
      php artisan migrate --force
