databases:
  - name: ai-mock-interviews-db

services:
  - type: web
    name: ai-mock-interviews-backend
    rootDir: backend
    plan: free
    autoDeploy: true
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: FRONTEND_ORIGIN
        value: https://surya-ray1.github.io
      - key: APP_KEY
        sync: false
      - key: DATABASE_URL
        fromDatabase:
          name: ai-mock-interviews-db
          property: connectionString
    buildCommand: |
      composer install --no-dev --prefer-dist --optimize-autoloader
      php artisan config:cache
      php artisan route:cache
      php artisan view:cache
      php artisan storage:link || true
    startCommand: |
      php -d variables_order=EGPCS -S 0.0.0.0:$PORT -t public public/index.php
    postDeployCommand: |
      php artisan migrate --force
