services:
  - type: web
    name: ai-mock-interviews-backend
    env: docker
    rootDir: backend
    plan: free
    autoDeploy: true
    envVars:
      # Database (Railway MySQL recommended for free tier)
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        sync: false
      - key: DB_PORT
        sync: false
      - key: DB_DATABASE
        sync: false
      - key: DB_USERNAME
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: APP_ENV
        value: production
      - key: APP_DEBUG
        value: false
      - key: LOG_CHANNEL
        value: stderr
      - key: QUEUE_CONNECTION
        value: sync
      - key: SESSION_DRIVER
        value: file
      - key: FRONTEND_ORIGIN
        value: https://surya-ray1.github.io
      - key: APP_KEY
        sync: false
      # If you prefer a single URL instead of individual DB_* vars, add
      # - key: DATABASE_URL
      #   sync: false
  # Dockerfile in backend/ will handle build, runtime caches, and migrations
